imports:
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    clusterId: '[Your PROD cluster ID]'
    orgId: '[Your PROD orgId]' # Azure Databricks only
    workspace:
      baseDir: '/__myproject__'
